<?php
/**
 * Created by PhpStorm.
 * User: ed
 * Date: 2020/4/8
 * Time: 下午 04:05
 */

namespace Modules\Node\Constants;

class LotteryClassifiedCodeConstants
{
    const MANAGE_LOTTERY_CLASSIFIED = 'MANAGE_LOTTERY_CLASSIFIED';
    const MANAGE_LOTTERY_CLASSIFIED_READ = 'MANAGE_LOTTERY_CLASSIFIED_READ';
    const MANAGE_LOTTERY_CLASSIFIED_CREATE = 'MANAGE_LOTTERY_CLASSIFIED_CREATE';
    const MANAGE_LOTTERY_CLASSIFIED_UPDATE = 'MANAGE_LOTTERY_CLASSIFIED_UPDATE';
    const MANAGE_LOTTERY_CLASSIFIED_DELETE = 'MANAGE_LOTTERY_CLASSIFIED_DELETE';
}
