<?php
/**
 * Created by PhpStorm.
 * User: ed
 * Date: 2020/3/16
 * Time: 上午 11:46
 */

namespace Modules\Node\Constants;

class NodeCodeConstants
{
    const MANAGE_ACCOUNT = 'MANAGE_ACCOUNT';
    const MANAGE_ACCOUNT_READ = 'MANAGE_ACCOUNT_READ';
    const MANAGE_ACCOUNT_CREATE = 'MANAGE_ACCOUNT_CREATE';
    const MANAGE_ACCOUNT_UPDATE = 'MANAGE_ACCOUNT_UPDATE';
    const MANAGE_ACCOUNT_DELETE = 'MANAGE_ACCOUNT_DELETE';
    const MANAGE_ROLE_CUSTOM = 'MANAGE_ROLE_CUSTOM';
    const MANAGE_ROLE_CUSTOM_READ = 'MANAGE_ROLE_CUSTOM_READ';
    const MANAGE_ROLE_CUSTOM_CREATE = 'MANAGE_ROLE_CUSTOM_CREATE';
    const MANAGE_ROLE_CUSTOM_UPDATE = 'MANAGE_ROLE_CUSTOM_UPDATE';
    const MANAGE_ROLE_CUSTOM_DELETE = 'MANAGE_ROLE_CUSTOM_DELETE';
    const ROLE_PUBLIC_AUTHORIZATION = 'ROLE_PUBLIC_AUTHORIZATION';
    const ROLE_PUBLIC_AUTHORIZATION_READ = 'ROLE_PUBLIC_AUTHORIZATION_READ';
    const ACCOUNT_LOGIN_HISTORY = 'ACCOUNT_LOGIN_HISTORY';
    const ACCOUNT_LOGIN_HISTORY_READ = 'ACCOUNT_LOGIN_HISTORY_READ';
}
